### PR TITLE
[CSL-1769] Remove handler from root logger

### PR DESCRIPTION
**Pull request by volhovm**

### CODE REVIEW

**Comment by chshersh** [comment]
@volhovM Could you please explain motivation behind this change?

**Comment by volhovm** [comment]
Without it, even if `initTerminalLogging` is not called, terminal logging is enabled (but is terribly ugly). Which doesn't make sense.

**Review by chshersh — APPROVED** [review]

**Comment by chshersh** [comment]
Bump up version and upload to Hackage :)

**Comment by chshersh** [comment]
You can even write to CHANGELOG.md

**Review by int-index — APPROVED** [review]
I tested this patch and it fixes the issue I had in CSL.

**Pull request merged**
